### ISSUE TITLE
Can the MSRV be lowered to 1.57 (or lower)?

### ISSUE THREAD

**Issue by jkugelman** [BurntSushi/bstr#135]
Is it possible to lower the MSRV from 1.60? I would love to use `bstr` at my company. It would give us a really nice answer for how to parse untrusted string data from network packets. Unfortunately we are stuck at Rust 1.57 for a while to maintain ABI compatibility with an external component that we have to support for another 1-2 years.

I see that `Cargo.toml` uses some of the feature/dependency capabilities introduced in 1.60.

```toml
std = ["alloc", "memchr/std", "serde?/std"]
alloc = ["serde?/alloc"]
unicode = ["dep:once_cell", "dep:regex-automata"]
serde = ["dep:serde"]
```

When I remove the new syntax and run `cargo +1.57 test --all-features` everything compiles and the tests pass.
